# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('shortname', models.CharField(max_length=5, unique=True, verbose_name='Kürzel')),
                ('type', models.CharField(max_length=50, verbose_name='Gesellschaftstyp')),
            ],
            options={
                'verbose_name': 'Gesellschaft',
                'verbose_name_plural': 'Gesellschaften',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('shortname', models.CharField(max_length=5, verbose_name='Kürzel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('closed', models.BooleanField(default=False, verbose_name='Geschlossen')),
                ('py_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_py_version', to='core.Version', verbose_name='Vorjahresversion')),
                ('tu_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_tu_version', to='core.Version', verbose_name='Matching-Version')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versionen',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='Gesellschaft')),
                ('prior_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Year', verbose_name='Vorjahr')),
            ],
            options={
                'verbose_name': 'Wirtschaftsjahr',
                'verbose_name_plural': 'Wirtschaftsjahre',
            },
        ),
        migrations.AddField(
            model_name='version',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Year', verbose_name='Jahr'),
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together=set([('company', 'end_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('year', 'shortname')]),
        ),
    ]
