# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='py_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_py_version', to='core.Version', verbose_name='Vorjahresversion'),
        ),
        migrations.AlterField(
            model_name='version',
            name='tu_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_tu_version', to='core.Version', verbose_name='Matching-Version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Year', verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='year',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Company', verbose_name='Gesellschaft'),
        ),
    ]
