# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20161011_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('sorting', models.PositiveSmallIntegerField(verbose_name='Sortierung/Position')),
            ],
            options={
                'verbose_name': 'Bilanzlinie',
                'verbose_name_plural': 'Bilanzlinien',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='Difference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2016-10-14 21:53:39.711482', max_length=160)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('local_gaap', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tax_gaap', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('pl_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('oci_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('pl_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('oci_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('oci', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_local_gaap', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_tax_gaap', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_pl_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_oci_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_pl_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_oci_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('py_oci', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_local_gaap', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_tax_gaap', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_pl_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_oci_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_permanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_pl_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_oci_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_temporary', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('tu_oci', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('pl_true_up', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('pl_movement', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('bs_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balancesheet.BsLineItem')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Difference_version', to='core.Version')),
            ],
            options={
                'verbose_name': 'Differenz',
                'verbose_name_plural': 'Differenzen',
                'ordering': ['name'],
            },
        ),
    ]
