# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difference',
            name='name',
            field=models.CharField(default='2016-10-14 21:54:23.369878', max_length=160),
        ),
    ]
