# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancesheet', '0005_auto_20161017_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='difference',
            name='pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='difference',
            name='py_pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='difference',
            name='tu_pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='difference',
            name='name',
            field=models.CharField(default='2016-10-31 21:43:06.241448', max_length=160),
        ),
    ]
