# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancesheet', '0007_auto_20161031_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='difference',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='difference',
            name='name',
            field=models.CharField(default='2016-11-05 23:43:25.945931', max_length=160),
        ),
    ]
